// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopOnline.Api.Data;

#nullable disable

namespace ShopOnline.Api.Migrations
{
    [DbContext(typeof(ShopOnlineDbContext))]
    [Migration("20240129233921_updateprice")]
    partial class updateprice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShopOnline.Api.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ShopOnline.Api.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ShopOnline.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Stylish and trendy traditional white pearl gold jhumka",
                            ImageURL = "/Images/Earrings/Earrings1.png",
                            Name = "White Pearl Gold Drop Jhumka",
                            Price = 50m,
                            Qty = 200
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Muticolor stone statement earring, captivating crystal and an eye catchy lion drop",
                            ImageURL = "/Images/Earrings/Earrings2.png",
                            Name = "Contemporary Crystal Stone",
                            Price = 50m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Handcrafted in silver and brass alloy with cz stones",
                            ImageURL = "/Images/Earrings/Earrings3.png",
                            Name = "Red Ruby Stones",
                            Price = 20m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Gold and white earrings featured the iconic image of Radha and Krishna ",
                            ImageURL = "/Images/Earrings/Earrings4.png",
                            Name = "Kundan Bahubali Earrings ",
                            Price = 50m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Black and gold plated enamelled dome shaped jhumkas",
                            ImageURL = "/Images/Earrings/Earrings5.png",
                            Name = "Dome shaped Jhumkas",
                            Price = 30m,
                            Qty = 85
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Gold plated set of 12 classy design",
                            ImageURL = "/Images/Bangles/Bangles1.png",
                            Name = "Gold Set of 12",
                            Price = 100m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Premium quality brass base opeable bangle with multiple stones",
                            ImageURL = "/Images/Bangles/Bangles2.png",
                            Name = "Brass Openable Kada",
                            Price = 40m,
                            Qty = 200
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Alloy base material with white beads",
                            ImageURL = "/Images/Bangles/Bangles3.png",
                            Name = "Gold Beaded Bangle",
                            Price = 40m,
                            Qty = 300
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Enameled gold plated leaf shaped bangle set",
                            ImageURL = "/Images/Bangles/Bangles4.png",
                            Name = "Leaf Shaped bangle Set",
                            Price = 600m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Traditional Blue and Golden color jumuka bangle set",
                            ImageURL = "/Images/Bangles/Bangles5.png",
                            Name = "Jumuka Bangle Set",
                            Price = 100m,
                            Qty = 15
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Rajwadhi plated elephant design brass kada",
                            ImageURL = "/Images/Bangles/Bangles6.png",
                            Name = "Elephant Design Kada",
                            Price = 100m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Golden necklace with laxmi pendant and green color stones",
                            ImageURL = "/Images/Necklaces/Necklaces1.png",
                            Name = "Laxmi Pendant Necklace",
                            Price = 50m,
                            Qty = 212
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Three layered red color beaded neckpiece",
                            ImageURL = "/Images/Necklaces/Necklaces2.png",
                            Name = "Red Beaded Necklace",
                            Price = 50m,
                            Qty = 112
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Alloy base material yellow gold plating necklace ",
                            ImageURL = "/Images/Necklaces/Necklaces3.png",
                            Name = "Golden Necklace",
                            Price = 70m,
                            Qty = 90
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Alloy material with gold antique tassel necklace",
                            ImageURL = "/Images/Necklaces/Necklaces4.png",
                            Name = "Antique Tassel Necklaces",
                            Price = 120m,
                            Qty = 95
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Handcrfted in brass alloy with ruby, pearl and meenakari work",
                            ImageURL = "/Images/Necklaces/Necklaces5.png",
                            Name = "Red Ruby Necklace",
                            Price = 15m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Golden brahmamudi long mangalsuthra with single vathi",
                            ImageURL = "/Images/Necklaces/Necklaces6.png",
                            Name = "Long Mangalsuthra",
                            Price = 20m,
                            Qty = 73
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Bridal baraat muti-colored patterend angle",
                            ImageURL = "/Images/Anklets/Anklets1.png",
                            Name = "Baraat Patterened Angle",
                            Price = 100m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Beaurtifil Copper alloy polki's with white beads",
                            ImageURL = "/Images/Anklets/Anklets2.png",
                            Name = "Polki's Anklet",
                            Price = 150m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Simple light weight elegant golden chain anklet",
                            ImageURL = "/Images/Anklets/Anklets3.png",
                            Name = "Golden Chain Anklet",
                            Price = 200m,
                            Qty = 70
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Beautiful simple silver paecock design anklet",
                            ImageURL = "/Images/Anklets/Anklets4.png",
                            Name = "Peacock Design Anklet",
                            Price = 120m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "Simple round shaped gold anklet",
                            ImageURL = "/Images/Anklets/Anklets5.png",
                            Name = "Gold Anklet",
                            Price = 100m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Gold Plated anklet with muticolored stones",
                            ImageURL = "/Images/Anklets/Anklets6.png",
                            Name = "Gold Stone Anklet",
                            Price = 50m,
                            Qty = 150
                        });
                });

            modelBuilder.Entity("ShopOnline.Api.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Earring"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Necklace"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bangles/Bracelets"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Anklet"
                        });
                });

            modelBuilder.Entity("ShopOnline.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Sarah"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
